[package]
name = "calculate_month_until_date"
version = "0.1.0"
authors = ["alejandro0619"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"